{% set name = "ogb" %}
{% set version = "1.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ogb-{{ version }}.tar.gz
  sha256: 15694f99a59e8c752022a89237228523d89e1963a3c19c81e0927c88927d28fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - outdated
    - pip
    - python >=3.6
  run:
    - numpy >=1.16.0
    - outdated >=0.2.0
    - pandas >=0.24.0
    - python >=3.6
    - scikit-learn >=0.20.0
    - six >=1.12.0
    - pytorch >=1.6.0
    - tqdm >=4.29.0
    - urllib3 >=1.24.0

test:
  imports:
    - ogb
    - ogb.graphproppred

about:
  home: https://github.com/snap-stanford/ogb
  summary: Open Graph Benchmark
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
