{% set name = "ogb" %}
{% set version = "1.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ogb-{{ version }}.tar.gz
  sha256: ce90418a0e3206483187aa7b7ecac1a2c5d85b3b99aceedb807138ee43115914

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - outdated
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.16.0
    - outdated >=0.2.0
    - pandas >=0.24.0
    - python >={{ python_min }}
    - scikit-learn >=0.20.0
    - six >=1.12.0
    - pytorch >=1.6.0
    - tqdm >=4.29.0
    - urllib3 >=1.24.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - ogb
    - ogb.graphproppred

about:
  home: https://github.com/snap-stanford/ogb
  summary: Open Graph Benchmark
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
