{% set name = "ogb" %}
{% set version = "1.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ogb-{{ version }}.tar.gz
  sha256: c6b975d85136c33c249eb0e6b6f8263699d798e794f6e734c9362d84e6743e32

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - outdated
    - pip
    - python
  run:
    - numpy >=1.16.0
    - outdated >=0.2.0
    - pandas >=0.24.0
    - python
    - scikit-learn >=0.20.0
    - six >=1.12.0
    - pytorch >=1.2.0
    - tqdm >=4.29.0
    - urllib3 >=1.24.0

test:
  imports:
    - ogb
    - ogb.graphproppred
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snap-stanford/ogb
  summary: Open Graph Benchmark
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
